version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${DB_PASSWORD}' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      sqlserver:
        condition: service_healthy
    command:
      - -url=jdbc:sqlserver://sqlserver:1433;databaseName=InterviewDB;encrypt=true;trustServerCertificate=true
      - -user=sa
      - -password=${DB_PASSWORD}
      - -schemas=dbo
      - migrate
    volumes:
      - ./flyway/sql:/flyway/sql

volumes:
  sql_data:
